import random

class Question:
	def __init__(self,que,a,b,c,d,e,RC):
		self.que = que
		self.a = a
		self.b = b
		self.c = c
		self.d = d
		self.e = e
		self.RC = RC
		self.raspunsCorect = [self.a,self.b,self.c,self.d,self.e][RC]
		
	def __str__(self):
		return '{}\n{}\n{}\n{}\n{}\n{}\n'.format(self.que,self.a,self.b,self.c,self.d,self.e)


Q1 = Question('\n1. When can a Development Team cancel a Sprint?\n','A. It can’t. Only Product Owners can cancel Sprints.','B. When functional expectations are not well understood.','C. When the Product Owner is absent too often.','D. When the selected Product Backlog items for the Sprint become unachievable.','E. When a technical dependency cannot be resolved.',0)
Q2 = Question('\n2. How should a Development Team deal with non-functional requirements?\n','A. Ensure every Increment meets them','B. Make sure the release department understands these requirements, but it is not the Development Team’s responsibility.','C. Handle them during the Integration Sprint preceding the Release Sprint.','D. Assign them to the lead developers on the team.','',0)
Q3 = Question('\n3. Scrum has a role called “Project Manager”.\n','A. True','B. False','','','',1)
Q4 = Question('\n4. Which answer best describes the topics covered in Sprint Planning?\n','A. What to do and who will do it.','B. How conditions have changed and how the Product Backlog should evolve.','C. What can be done and how to do it.','D. What went wrong in the last Sprint and what to do differently this Sprint.','E. Who is on the team and what team member roles will be.',2)
Q5 = Question('\n5. Which of the following is required by Scrum?\n','A. Sprint Retrospective.','B. Members must be stand up at the Daily Scrum.','C. Sprint Burndown Chart.','D. Release planning.','E. All of the above.',0)
Q6 = Question('\n6. Who determines when it is appropriate to update the Sprint Backlog during a Sprint?\n','A. The Project Manager.','B. The Development Team.','C. The Scrum Team.','D. The Product Owner.','',1)
Q7 = Question('\n7. Who must attend the Daily Scrum?\n','A. The Scrum Master and Product Owner.','B. The Development Team.','C. The Development Team and Product Owner.','D. The Scrum Team.','E. The Development Team and Scrum Master.',1)
Q8 = Question('\n8. When do Development Team members take ownership of a Sprint Backlog item?\n','A. At the Sprint planning meeting.','B. During the Daily Scrum.','C. Never. All Sprint Backlog Items are “owned” by the entire Development Team, even though each one may be done by an individual Development Team member.','D. Whenever a team member can accommodate more work.','',2)
Q9 = Question('\n9. The purpose of a Sprint is to produce a done Increment of product.\n','A. True','B. False','','','',0)
Q10 = Question('\n10. Who creates the definition of “Done”?\n','A. The Scrum Master as he/she is responsible for the Development Team’s productivity.','B. The Scrum Team, in a collaborative effort where the result is the common denominator of all members’ definition.','C. The Product Owner as he/she is responsible for the product’s success.','D. The development organization (or Development Team if none is available from the development organization).','',3)
Q11 = Question('\n11. Five new Scrum Teams have been created to build one product. A few of the developers on one of the Development Teams ask the Scrum Master how to coordinate their work with the order teams. What should the Scrum Master do?\n','A. Teach the Product Owner to work with the lead developers on ordering Product Backlog in a way to avoid too much technical and development overlap during a Sprint.','B. Teach them that it is their responsibility to work with the other teams to create an integrated Increment.','C. Collect the Sprint tasks from the teams at the end of their Sprint Planning and merge that into a consolidated plan for the entire Sprint.','D. Visit the five teams each day to inspect that their Sprint Backlogs are aligned.','',2)
Q12 = Question('\n12. What does it mean to say that an event has a time-box?\n','A. The event must happen at a set time.','B. The event must happen by a given time.','C. The event must take at least a minimum amount of time.','D. The event can take no more than a maximum amount of time.','',3)
Q13 = Question('\n13. A properly functioning Scrum Team will have at least one Release Sprint and may well have several.\n','A. True','B. False','','','',0)
Q14 = Question('\n14. Scrum is a methodology that tells in detail how to build software incrementally.\n','A. True','B. False','','','',1)
Q15 = Question('\n15. For which is the Scrum Master responsible?\n','A. Managing the performance of the Scrum Team.','B. The meetings and the objectives that a Scrum Team sets for itself.','C. The Scrum framework being adopted and used properly.','D. Keeping track of resource allocation.','',2)
Q16 = Question('\n16. A Development Team asks their Product Owner to re-order the Product Backlog. The team is waiting for an external supplier to deliver a specific software component. Without that component there won’t be enough work in the next Sprint to occupy the full team. The Product Owner asks the Scrum Master for help. What would be good advice to give the Product Owner?\n','A. Remind the Product Owner that his primary concern is the flow of value reflected in the ordering of the Product Backlog.','B. Tell the Product Owner to re-order the Product Backlog so the work involving the external component can be planned in a separate sprint.','C. Tell the Product Owner that the Product Backlog should be ordered to maximize utilization of the Development Team.','','',0)
Q17 = Question('\n17. How often should Development Team membership change?\n','A. As needed, while taking into account a short term reduction in productivity','B. Never, because it reduces productivity.','C. As needed, with no special allowance for changes in productivity.','D. Every Sprint to promote shared learning.','',0)
Q18 = Question('\n18. Who should make sure everyone on the Development Team does his or her tasks for the Sprint?\n','A. The Project Manager.','B. The Product Owner.','C. The Scrum Master.','D. The Development Team.','E. All of the above.',3)
Q19 = Question('\n19. When is it most appropriate for a Development Team to change the definition of “Done”?\n','A. During Sprint Planning.','B. Prior to starting a new Sprint.','C. During the Sprint Retrospective.','D. Prior to starting a new project.','',2)
Q20 = Question('\n20. Which statement best describes Scrum?\n','A. A defined and predictive process that confirms to the principles of Scientific Management.','B. A complete methodology that defines how to develop software.','C. A cookbook that defines best practices for software development.','D. A framework within which complex products in complex environments are developed.','',3)
Q21 = Question('\n21. Who starts the Daily Scrum?\n','A. The person coming in last. This encourages people to be on time and helps to stay within the time-box','B. Whoever the Development Team decides should start.','C. The person who has the token.','D. The Scrum Master. This ensures that the Development Team has the meeting and stays within the time-box.','E. The person who last broke the build.',1)
Q22 = Question('\n22. Which of these may a Development Team deliver at the end of a Sprint?\n','A. Failing unit tests, to identify acceptance tests for the next Sprint.','B. An increment of software with minor known bugs in it.','C. An increment of working software that is “done”.','D. A single document, if that is what the Scrum Master asked for.','',2)
Q23 = Question('\n23. How much of the Sprint Backlog must be defined during the Sprint Planning event?\n','A. Just enough tasks for the Scrum Master to be confident in the Development Team’s understanding of the Sprint.','B. The entire Sprint Backlog must be identified and estimated by the end of the Sprint Planning meeting.','C. Enough so the Development Team can create its best forecast of what is can do, and to start the first several days of the Sprint.','D. Just enough to understand design and architectural implications.','',2)
Q24 = Question('\n24. The CEO asks the Development Team to add a “very important” item to a Sprint that is in progress. What should the Development Team do?\n','A. Add the item to the current Sprint and drop an item of equal size.','B. Add the item to the current Sprint without any adjustments.','C. Inform the Product Owner so he/she can work with the CEO.','D. Add the item to the next Sprint.','',2)
Q25 = Question('\n25. The time-box for a Daily Scrum?\n','A. Two minutes per person.','B. 15 minutes.','C. 15 minutes for a 4 week sprint. For shorter Sprints it is usually shorter.','D. 4 hours.','E. The same time of day every day.',1)
Q26 = Question('\n26. Which phrase best describes a Product Owner?\n','A. Go-between development team and customers.','B. Value optimizer.','C. Requirements engineer.','D. Team manager.','',0)
Q27 = Question('\n27. During a Sprint Retrospective, for what is the Product Owner responsible?\n','A. Participating as a Scrum Team member.','B. Summarizing and reporting the discussions to the stakeholders that he/she represents in the Scrum Team.','C. Capturing requirements for the Product Backlog.','D. The Product Owner should not take part in Sprint Retrospectives.','',0)
Q28 = Question('\n28. For the purpose of transparency, when does Scrum say a new increment of working software must be available?\n','A. After the acceptance testing phase.','B. Before the release Sprint.','C. Every 3 Sprints.','D. At the end of every Sprint.','E. When the Product Owner asks to create one.',3)
Q29 = Question('\n29. A Scrum Master is essentially the same thing as a traditional PM (Project Manager).\n','A. True','B. False','','','',1)
Q30 = Question('\n30. A Product Owner wants advice from the Scrum Master about estimating work in Scrum. Which of these is the guideline that a Scrum Master should give?\n','A. Product Backlog items must be estimated in story points','B. Estimates are made by the Development Team.','C. Estimates must be in relative units.','D. Scrum forbids estimating.','E. Estimates are made by the Product Owner, but are best checked with the Development Team.',1)
Q31 = Question('\n31. Which Scrum Value is affected by a lack of trust in the Scrum Team?\n','A. Focus','B. Respect','C. Openness','D. Courage','E. All of the above.',4)
Q32 = Question('\n32. A product Increment must be released to production at the end of each Sprint.\n','A. True','B. False','','','',1)
Q33 = Question('\n33. How is management external to the Scrum Team involved in the Daily Scrum?\n','A. The Scrum Master speaks on their behalf','B. The Development Team self-manages and is the only management required at the Daily Scrum.','C. Management gives an update at the start of each Daily Scrum.','D. The Product Owner represents their opinions','',1)
Q34 = Question('\n34. What is the time-box for the Sprint Review?\n','A. As long as needed.','B. 2 hours for a monthly Sprint','C. 4 hours for a monthly Sprint.','D. 4 hours and longer as needed.','E. 1 day',2)
Q35 = Question('\n35. Who is responsible for tracking the remaining work of the Sprint?\n','A. The Development Team.','B. The Scrum Master.','C. The Project Manager','D. The Development Team is consultation with the Product Owner.','E. The Product Owner.',0)
Q36 = Question('\n36. Which of the following best describes an increment of working software?\n','A. A decomposition of all Product Backlog items into tasks for future Sprint Backlog lists.','B. Additional features in a usable state that complement those delivered in previous iterations.','C. A new user interface design for functionality delivered in previous iterations.','D. An automated test suite to verify functionality delivered in previous iterations.','E. UML diagrams that describe how to deliver functionality in future iterations.',1)
Q37 = Question('\n37. The Product Owner determines how many Product Backlog items the Development Team selects for a Sprint.\n','A. False.','B. True, accordingly to what was committed to the stakeholders.','C. True, but only after confirmation by the resource manager that the Team has enough capacity.','D. True.','E. False, the Scrum Master does that.',0)
Q38 = Question('\n38. Which of the following services are appropriate for a Scrum Master in regard to the Daily Scrum?\n','A. Lead the discussions of the Development Team.','B. Make sure that all 3 questions have been answered by each member of the team.','C. Keep track of whether each team member has a chance to speak.','D. Teach the Development Team to keep the Daily Scrum within the 15 minute time-box.','E. All of the above.',3)
Q39 = Question('\n39. Which of the following might the Scrum Team discuss during a Sprint Retrospective?\n','A. Methods of communication.','B. The way the Scrum Team does Sprint Planning.','C. Skills needed to improve the Development Team’s ability to deliver.','D. Its Definition of “Done”.','E. All of the above.',4)
Q40 = Question('\n40. You are the Scrum Master of a new, to be developed product. Development is going to require 45 people. What is a good first question for you to suggest the group thinks about when forming into teams?\n','A. How will we make sure all teams have the right amount or expertise?','B. What is the right mixture of senior and junior people on each team?','C. Who are going to be the team leads?','D. Who are the subject matter experts on each team?','',0)
Q41 = Question('\n41. Cross-functional teams are optimized to work on one technical layer of a system only (e.g. GUI, database, middle tier, interfaces).\n','A. True','B. False','','','',1)
Q42 = Question('\n42. A Scrum Master is working with a Development Team that has members in different physical locations. The Development Team meets in a variety of meeting rooms and has much to do logistically (for example, set up conference calls) before the Daily Scrum. What action should the Scrum Master take?\n','A. Allow the Development Team to self-manage and determine for itself what to do.','B. Set up the meeting and tell the Development Team that is how it will be done.','C. Ask the Development Team members to alternate who is responsible for meeting setup.','D. Inform management and ask them to solve it.','',0)
Q43 = Question('\n43. Every Scrum team must have a Product Owner and Scrum Master.\n','A. True. Outcomes affected by their participation and availability.','B. False. A Product Owner can be replaced by a business analyst in the Development Team.','C. False. A Scrum Master is only required when asked for by the Development Team.','D. True. Each must be 100% dedicated to the Scrum Team.','',0)
Q44 = Question('\n44. The Sprint Goal is a result of Sprint Planning, as is the Sprint Backlog.\n','A. True','B. False','','','',0)
Q45 = Question('\n45. When should a Sprint Goal be created?\n','A. It should have been created in the previous Sprint during Product Backlog refinement.','B. It must be established before Sprint Planning in order to begin planning.','C. A Sprint Goal is not mandatory in Scrum.','D. At any time during the Sprint.','E. During Sprint Planning.',4)
Q46 = Question('\n46. In accordance with Scrum theory, how should a group of 100 people be divided into multiple Development Teams?\n','A. Understanding the product, the product vision and the rules of the Scrum framework, the group divides itself into teams.','B. It doesn’t really matter because you can rotate the teams every Sprint to spread knowledge.','C. Check with the allocation department to see who has worked together before and make these the first teams','D. Create a matrix of skills, seniority, and level of experience to assign people to teams.','',0)
Q47 = Question('\n47. A Sprint Retrospective should be held:\n','A. At the end of each Sprint.','B. At the beginning of each Sprint.','C. Only when the Scrum Team determines it needs one.','D. At the end of the last Sprint in a project or a release.','',0)
Q48 = Question('\n48. A new developer is having continuing conflicts with existing Development Team members and creating the hostile environment. If necessary, who is responsible for removing the team member?\n','A. The hiring manager is responsible, because he/she hired the developer','B. The Scrum Manager is responsible, because he/she removes Impediments.','C. The Development Team is responsible, and may need help from the Scrum Master','D. The Product Owner is responsible, because he/she controls the return on investment (ROI).','',1)
Q49 = Question('\n49. The Product Owner makes sure the team selects enough from the Product Backlog for a Sprint to satisfy the stakeholders.\n','A. True','B. False','','','',1)
Q50 = Question('\n50. Which statement best describes the Sprint Review?\n','A. It is used to congratulate the Development Team if it did what it forecast, or to punish the Development Team if it failed to meet its forecast.','B. It is a demo at the end of the Sprint for everyone in the organization to check on the work done.','C. It is a mechanism to control the Development Team’s activities during a Sprint.','D. It is when the Scrum Team and stakeholders inspect the outcome of a Sprint and figure out what to do next.','',3)
Q51 = Question('\n51. Who owns the Sprint Backlog?\n','A. The Scrum Team.','B. The Product Owner.','C. The Scrum Master.','D. The Development Team','',3)
Q52 = Question('\n52. Every Development Team should have:\n','A. At least one representative from each major software engineering discipline (like QA, Dev, UX).','B. The competencies and skills needed to deliver a Done Increment in a Sprint.','C. One Lead Developer and no more than 8 other members','','',1)
Q53 = Question('\n53. Why does the Product Owner want the Development Team to adhere to its definition of “Done”?\n','A. To have complete transparency into what has been done at the end of each Sprint.','B. To be able to reprimand the team when they don’t meet their velocity goal for the Sprint.','C. To know what the team will deliver over the next three Sprints.','D. To predict the team’s productivity over time.','',0)
Q54 = Question('\n54. The Development Team should have all the skills needed to:\n','A. Turn Product Backlog items into an Increment of potentially releasable product functionality.','B. Do all of the development work, except for specialized testing that requires additional tools and environments.','C. Complete the project within the date and cost as calculated by the Product Owner.','','',0)
Q55 = Question('\n55. When is implementation of a Product Backlog item considered complete?\n','A. At the end of the Sprint.','B. When the item has no work remaining in order to be potentially released.','C. When QA reports that the item passes all acceptance criteria.','D. When all work in the Sprint Backlog related to the item is finished.','',1)
Q56 = Question('\n56. A Scrum Master is introducing Scrum to a new Development Team. The Development Team gas decided that a Sprint Retrospective is unnecessary. What action should the Scrum Master take?\n','A. Call a meeting between the Development Team and senior management.','B. Comply with the decision of the self-organizing team.','C. Consult with the Product Owner to see how he/she feels about the situation.','D. Begin facilitating productive and useful Sprint Retrospectives.','',3)
Q57 = Question('\n57. When does the second Sprint start?\n','A. Once the architectural changes for the second Sprint have been approved by the senior architect.','B. After the Product Backlog for the second Sprint has been selected.','C. Immediately after the first Sprint.','D. After the customer completes acceptance testing of the first Sprint.','',2)
Q58 = Question('\n58. What is included in the Sprint Backlog?\n','A. User Stories.','B. Tasks.','C. Use Cases.','D. Tests.','E. Any of the above (or others) which are a decomposition of the selected Product Backlog items.',4)
Q59 = Question('\n59. Why should the Product Owner be present at the Daily Scrum?\n','A. He/She doesn’t need to be there.','B. To hear about impediments in functionality.','C. To represent the stakeholders’ point of view.','D. To participate as a Scrum Team member.','',0)
Q60 = Question('\n60. Who is responsible for clearly expressing Product Backlog items?\n','A. The Scrum Master, or the Scrum Master may have the Development Team do it.','B. The Scrum Master.','C. The Product Owner.','D. The business analyst who represents the Product Owner in the Development Team.','',2)
Q61 = Question('\n61. If burndown charts are used to visualize progress, what does a trend line through a release burndown chart indicate?\n','A. The evolution of the cost spent on the project.','B. When all work will be completed to the Scrum Team can be released for other work.','C. When the work remaining will likely be completed if nothing changes on the Product Backlog or the Development Team.','D. When the project will be over if the Product Owner removes work that is equal in effort to any new work that is added.','',2)
Q62 = Question('\n62. Who is responsible for engaging the stakeholders?\n','A. The Business Analyst.','B. The Development Team.','C. The Team Manager.','D. The Project Manager.','E. The Product Owner',4)
Q63 = Question('\n63. How much work must a Development Team do to a Product Backlog item it selects for a Sprint?\n','A. A proportional amount of time on analysis, design, programming, testing, and documentation.','B. As much as it can fit into the Sprint. Any remaining work will be transferred to a subsequent Sprint','C. All development work and at least some testing.','D. As much as it has told the Product Owner will be done for every Product Backlog item it selects in conformance with the definition of “Done”.','',3)
Q64 = Question('\n64. Which statement best describes the Sprint Backlog as outcome of the Sprint Planning?\n','A. It is a complete list of all work to be done in a Sprint','B. Every item has a designated owner.','C. Each task is estimated in hours.','D. It is the Development Team s plan for the Sprint.','E. It is ordered by the Product Owner.',0)
Q65 = Question('\n65. Sprint burndown charts are an efficient tracking tool, because they show:\n','A. An estimate of the total work remaining for the Sprint.','B. How much effort has gone into a Sprint.','C. How many hours have been worked by each Development Team member.','D. How many Product Backlog items remain.','',0)
Q66 = Question('\n66. User documentation is part of your definition of “Done”. However, there aren t enough technical writers for all teams. Your Development Team doesn\'t have a technical writer. What should you do?\n','A. Form a separate team of technical writers that will work on an on-demand basis for the various Product Owners. Work order will be first in, first out.','B. Let the user documentation remain undone and accumulate until after the last development Sprint. It will then be done by any available technical writers.','C. Wait until you have a technical writer on your Development Team to take care of this.','D. Your Development Team is still responsible for creating user documentation. In this case, the Development Team members will write it.','',3)
Q67 = Question('\n67. Which best describes the Product Backlog?\n','A. It is allowed to grow and change as more is learned about the product and its customers.','B. It provides just enough information to enable a Scrum team to start the design phase of a product.','C. It contains all foreseeable tasks and requirements from which the Scrum team can develop and maintain a complete project plan.','D. It is baselined to follow change management processes.','',0)
Q68 = Question('\n68. The Product Owner must release each Increment to production\n','A. When it makes sense.','B. To make sure the Development Team is done every Sprint.','C. Whenever the product is free of defects.','D. Without exception.','',0)
Q69 = Question('\n69. During a Sprint, when is new work or further decomposition of work added to the Sprint Backlog?\n','A. When the Product Owner identifies new work.','B. As soon as possible after they are identified.','C. When the Scrum Master has time to enter them.','D. During the Daily Scrum after the Development Team approves them.','',1)
Q70 = Question('\n70. What it the main reason for the Scrum Master to be at the Daily Scrum?\n','A. To gather status and progress information to report to management.','B. To write down any changes to the Sprint Backlog, including adding new items, and tracking progress on the burn-down.','C. He or she does not have to be there; he or she only has to ensure the Development Team has a Daily Scrum.','D. To make sure every team member answers the three questions.','',2)
Q71 = Question('\n71. You have six teams using a traditional method to deliver a product. Your management has asked you to start using Scrum. In the initial project there were separate plans and teams for the layers of a software system, i.e. one for the front-end, one for the middle tier, one for the back-end, and one for the interfaces and services.This resembles what is known as component teams. But you have read that it’s a good idea to have teams organized by feature. What are the advantages of keeping component teams while starting Scrum?\n','A. There’s less initial disruption than organizing into new teams. As they start, they will discover what works best, and how to potentially re-organize towards this','B. Component teams generally have the skills needed to create a working Increment of software that provides business value.','C. Because they have worked together for some time, they are likely able to start producing shippable Increments faster that new feature teams would.','D. There are fewer cross-team dependencies than working in feature teams.','',0)
Q72 = Question('\n72. How should Product Backlog items be chosen when multiple Scrum Teams work from the same Product Backlog?\n','A. The Scrum Team with the highest velocity pulls Product Backlog items first.','B. The Development Teams pull in work in agreement with the Product Owner','C. The Product Owner should provide each team with its own Product Backlog.','D. Each Scrum Team takes an equal numbers of items.','E. The Product Owner decides.',1)
Q73 = Question('\n73. How often should Development Team membership change?\n','A. As needed, while taking into account a short term reduction in productivity.','B. Never, because it reduces productivity.','C. As needed, with no special allowance for changes in productivity.','D. Every Sprint to promote shared learning.','',0)
Q74 = Question('\n74. Who is responsible for managing the progress of work during a Sprint?\n','A. The Scrum Master.','B. The Development Team.','C. The Product Owner.','D. The most junior member of the Team.','',1)
Q75 = Question('\n75. What is the role of management in Scrum?\n','A. To facilitate the Scrum Teams with insights and resources that help them improve.','B. To monitor the Development Team’s productivity.','C. To identify and remove people that aren’t working hard enough.','D. To continually monitor staffing levels of the Development Team.','',0)
Q76 = Question('\n76. Which technique is the best way the Scrum Master can ensure that the Development Team communicates effectively with the Product Owner?\n','A. Monitor communications between them and facilitate direct collaboration.','B. Teach the Development Team to talk in terms of business needs and objectives.','C. Teach the Product Owner about the technologies employed during the Sprints.','D. Act as a go-between for them.','',0)
Q77 = Question('\n77. The length of a Sprint should be:\n','A. Short enough to keep the business risk acceptable to the Product Owner','B. Short enough to be able to synchronize the development work with other business events.','C. No more than one calendar month.','D. All of these answers are correct.','',0)
Q78 = Question('\n78. What is the time-box for the Sprint Planning meeting?\n','A. 4 Hours for a monthly Sprint','B. 8 Hours for a monthly Sprint.','C. Monthly.','D. Whenever it is done.','',1)
Q79 = Question('\n79. If burndown charts are used to visualize progress, what do they track?\n','A. Accumulated cost.','B. Individual worker productivity.','C. Work remaining across time.','D. Accumulated business value delivered to the customer.','',2)
Q80 = Question('\n80. To get started in terms of what to build, Scrum requires no more than a Product Owner with enough ideas for a first Sprint, a Development Team to implement those ideas and a Scrum Master to help guide the process.\n','A. True','B. False','','','',0)
Q81 = Question('\n81. What is the tactic a Scrum Master should use to divide a group of 100 people into multiple Development Teams?\n','A. Create teams based on their skills across multiple layers (such as database, UI, etc.)','B. Ask the Product Owner to assign the people to teams.','C. Ask the developers to divide themselves into teams.','','',2)
Q82 = Question('\n82. Which statement best describes a Product Owner’s responsibility?\n','A. Optimizing the value of the work the Development Team does.','B. Managing the project and ensuring that the work meets the commitments to the stakeholders','C. Directing the Development Team.','D. Keeping stakeholders at bay.','',0)
Q83 = Question('\n83. The Sprint Review is mainly an inspect and adapt opportunity for which group?\n','A. The Development Team and stakeholders','B. The Product Owner and Development Team.','C. The Scrum Team and stakeholders','D. The Product Owner and management.','E. The Development Team and management.',2)
Q84 = Question('\n84. When a Development Team is having trouble delivering a working Increment because they don’t understand a functional requirement, what should they do?\n','A. Add a specialist to the Development Team.','B. Partially complete the functionality, and discuss the remaining work at the Sprint Review.','C. Collaborate with the Product Owner to determine what is possible and acceptable.','D. Defer the work to a more appropriate Sprint.','',2)
Q85 = Question('\n85. Who can abnormally terminate a Sprint?\n','A. The Scrum Master','B. The Development Team or its members.','C. The Product Owner','D. The Stakeholders','',2)
Q86 = Question('\n86. During a Sprint Retrospective, for what is the Scrum Master responsible?\n','A. Prioritizing the resulting action items.','B. Participating as a Scrum team member and facilitating as requested or needed.','C. Acting as a scribe to capture the Development Team’s answers.','D. Summarizing and reporting the discussions to management.','',1)
Q87 = Question('\n87. What enhances the transparency of an increment?\n','A. Doing all work needed to meet the definition of “Done”','B. Reporting Sprint progress to the stakeholders daily','C. Keeping track of and estimating all undone work to be completed in a separate Sprint','D. Updating Sprint tasks properly in the electronic tracking tool.','',0)


qdb = [Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,Q11,Q12,Q13,Q14,Q15,Q16,Q17,Q18,Q19,Q20,Q21,Q22,Q23,Q24,Q25,Q26,Q27,Q28,Q29,Q30,Q31,Q32,Q33,Q34,Q35,Q36,Q37,Q38,Q39,Q40,Q41,Q42,Q43,Q44,Q45,Q46,Q47,Q48,Q49,Q50,Q51,Q52,Q53,Q54,Q55,Q56,Q57,Q58,Q59,Q60,Q61,Q62,Q63,Q64,Q65,Q66,Q67,Q68,Q69,Q70,Q71,Q72,Q73,Q74,Q75,Q76,Q77,Q78,Q79,Q80,Q81,Q82,Q83,Q84,Q85,Q86,Q87]

while True:
	n = random.choice(qdb)
	print(n)
	userInput = input()
	if userInput == 'a':
		userInput = n.a
	elif userInput == 'b':
		userInput = n.b
	elif userInput == 'c':
		userInput = n.c
	elif userInput == 'd':
		userInput = n.d
	elif userInput == 'e':
		userInput = n.e
	if userInput == n.raspunsCorect:
		print('\n ------------------------------  Correct !  ------------------------------\n\n Next Question:')
	else:
		print('\n------------------------------  WRONG  ------------------------------\nThe correct answer is: ' + n.raspunsCorect + '\n---------------------------------------------------------------------\n\n Next Question:')